# Generated by Django 3.0.6 on 2020-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=32)),
                ('point_type', models.CharField(max_length=32, null=True)),
                ('section', models.CharField(max_length=32, null=True)),
                ('X', models.FloatField(null=True)),
                ('Y', models.FloatField(null=True)),
                ('Z', models.FloatField(null=True)),
                ('X_touyin', models.FloatField(null=True)),
                ('Y_touyin', models.FloatField(null=True)),
                ('Z_touyin', models.FloatField(null=True)),
                ('coordinates', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElevationPointFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=32, null=True)),
                ('file_name', models.CharField(max_length=32, null=True)),
                ('coordinates', models.TextField(null=True)),
                ('shp_file', models.FileField(upload_to='shapefile')),
            ],
        ),
    ]
