# Generated by Django 3.0.6 on 2020-05-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcGIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevationpointfile',
            name='section',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='elevationpointfile',
            name='shp_file',
            field=models.FileField(upload_to='shapefilezip'),
        ),
    ]
